### ISSUE TITLE
[Question] - Can we receive more information from TickTimer Task

### ISSUE THREAD

**Issue by codingwatching** [DonnYep/CosmosFramework#12]
Hi @DonnYep 
I am using CosmosFramework to implement this game requirement:
- The enemy will spawn in some future time
So I use addTask and set the delayTime to handle this
But in the future, I need to know what enemy name (or enemy id) to spawn, for now, only task id is return.
I am thinking about adding userData to Task construction, so when we call TaskCallback, we pass it like this
```
task.TaskCallback.Invoke(task.TaskId,task.UserData);
```

Is there another way to do it? Thank you so much, I am learning CosmosFramework every day

**Comment by DonnYep** [comment]
Hi @codingwatching 
The tickTimer is only used as a timer, it does not have the ability to record userData. If you need to get more information from tickTimer, you should design the code to do so, rather than relying on a data structure. Spawn the object is the job of objectPool or entity. When you spawn the object with objectPool or entity, you can get information about the spawned objects by listening to the corresponding events.
I hope it can help you, in addition I will update the entity example as soon as possible : )

**Comment by codingwatching** [comment]
@DonnYep Yes I am going to design a class with a tick timer and Spawner together inside the Class
Thank you so much! Yes, an entity example would be great for me to follow the Entity pattern!
