### ISSUE TITLE
[UI Manager] - Should we add some default Layers and some Tweening function

### ISSUE THREAD

**Issue by codingwatching** [DonnYep/CosmosFramework#17]
Hi @DonnYep 
It is only my suggestion, currently, the UI in our Framework is simple and easy to use enough.
 - Add some layer node likes: Top Layer, Middle Layer, Bottom Layer, or some parent as a placeholder for the panel group 
 - Add basic Tweenning function  for UI components before and after Panel Open and Close (Need some async function to await the tweens to completed)
Thank you so much! Have a nice day!

**Comment by DonnYep** [comment]
Hi @codingwatching 

Thanks for the suggestion.

1. The Order property of IUIForm controls the rendering order of ui, which is more customizable than the top middle bottom layer. In addition ui module is to support the group function, I recommend that these are actually handled in the specific project, rather than in the framework to do support.

2. UI Module manages the interface IUIFrom, not UGUIUIForm, so users can customize the uiform base class. If you refer to UGUIUIForm to customize uifrom base class, you can implement tween transition in OnClose OnOpen functions. ui module of CF is compatible with fgui and ugui, so it does not support tween specifically for one ui solution. Each project will have different tween needs, so the project will develop a ui system specifically for the business on top of the framework. This system can include top middle bottom ui layering, tween, tips, mask, and panel group, etc.

Thank you very much for always following my code and making suggestions. Have a nice day!

**Comment by DonnYep** [comment]
Hi @codingwatching

Thanks for the suggestion.

The Order property of IUIForm controls the rendering order of ui, which is more customizable than the top middle bottom layer. In addition ui module is to support the group function, I recommend that these are actually handled in the specific project, rather than in the framework to do support.

UI Module manages the interface IUIFrom, not UGUIUIForm, so you can customize the uiform base class. If you refer to UGUIUIForm to customize uifrom base class, you can implement tween transition in OnClose OnOpen functions. UI module of CF is compatible with fgui and ugui, so it does not support tween specifically for one ui solution. Each project will have different tween needs, so the project will develop a ui system specifically for the business based on the framework. This system can include top middle bottom ui layering, tween, tips, mask, and panel group, etc.

Thank you very much for always following my code and making suggestions. Have a nice day!

**Comment by codingwatching** [comment]
Hi @DonnYep 
Awesome! I just understand 
- Order (From the 03_UI we have Status Panel always on top with Order set to 1)
- IUIForm and UGUIUIForm and UGUIAssetHelper
It really helps me a lot to implement the detailed UI for my game
Thank you so much for the explanation!
